# Generated by Django 2.0.2 on 2018-04-03 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_history', models.CharField(max_length=1000)),
                ('mat_name', models.CharField(max_length=1000)),
                ('path', models.FilePathField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.LogFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
