# Generated by Django 2.0.2 on 2018-05-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='log',
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='user',
        ),
        migrations.DeleteModel(
            name='Matrix',
        ),
    ]
