# Generated by Django 2.0.2 on 2018-04-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='log_dir',
        ),
    ]
