# Generated by Django 2.0.2 on 2018-04-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_logfile_log_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='regex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
