# Generated by Django 2.0.2 on 2018-05-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_logfile_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='log_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
