# Generated by Django 2.0.2 on 2018-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20180430_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='logfile',
            name='log_name',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
