# Generated by Django 2.0.2 on 2018-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20180430_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='log_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='logfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
